# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/90a80c09-2af6-4ff2-86e2-2b3b0cba6536";
      fsType = "ext4";
    };

  fileSystems."/mnt/nvme2" =
    { device = "/dev/disk/by-uuid/b4c58fe6-2f9e-4fd6-8e19-f7c48a8bc5d4";
      fsType = "ext4";
    };

  fileSystems."/mnt/hdd1" =
    { device = "/dev/disk/by-uuid/fa0a8dcf-381b-47be-971b-1ac242ef3cab";
      fsType = "ext4";
    };

  fileSystems."/mnt/sdd" =
    { device = "/dev/disk/by-uuid/709d2aee-054d-4cc5-a979-74ea4d05cff9";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/421D-F5B8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ec6eac78-0b61-41d3-933a-baa267d5535c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
